export const cities = [
  { name: "New York", slug: "new-york", keyword: "AI dental software New York" },
  { name: "Los Angeles", slug: "los-angeles", keyword: "AI dental software Los Angeles" },
  { name: "Chicago", slug: "chicago", keyword: "AI dental software Chicago" },
  { name: "Houston", slug: "houston", keyword: "AI dental software Houston" },
  { name: "Phoenix", slug: "phoenix", keyword: "AI dental software Phoenix" },
  { name: "Philadelphia", slug: "philadelphia", keyword: "AI dental software Philadelphia" },
  { name: "San Antonio", slug: "san-antonio", keyword: "AI dental software San Antonio" },
  { name: "San Diego", slug: "san-diego", keyword: "AI dental software San Diego" },
  { name: "Dallas", slug: "dallas", keyword: "AI dental software Dallas" },
  { name: "San Jose", slug: "san-jose", keyword: "AI dental software San Jose" },
  { name: "Austin", slug: "austin", keyword: "AI dental software Austin" },
  { name: "Jacksonville", slug: "jacksonville", keyword: "AI dental software Jacksonville" },
  { name: "Fort Worth", slug: "fort-worth", keyword: "AI dental software Fort Worth" },
  { name: "Columbus", slug: "columbus", keyword: "AI dental software Columbus" },
  { name: "Charlotte", slug: "charlotte", keyword: "AI dental software Charlotte" },
  { name: "San Francisco", slug: "san-francisco", keyword: "AI dental software San Francisco" },
  { name: "Indianapolis", slug: "indianapolis", keyword: "AI dental software Indianapolis" },
  { name: "Seattle", slug: "seattle", keyword: "AI dental software Seattle" },
  { name: "Denver", slug: "denver", keyword: "AI dental software Denver" },
  { name: "Washington", slug: "washington", keyword: "AI dental software Washington" },
  { name: "Boston", slug: "boston", keyword: "AI dental software Boston" },
  { name: "El Paso", slug: "el-paso", keyword: "AI dental software El Paso" },
  { name: "Nashville", slug: "nashville", keyword: "AI dental software Nashville" },
  { name: "Detroit", slug: "detroit", keyword: "AI dental software Detroit" },
  { name: "Oklahoma City", slug: "oklahoma-city", keyword: "AI dental software Oklahoma City" },
  { name: "Portland", slug: "portland", keyword: "AI dental software Portland" },
  { name: "Las Vegas", slug: "las-vegas", keyword: "AI dental software Las Vegas" },
  { name: "Memphis", slug: "memphis", keyword: "AI dental software Memphis" },
  { name: "Louisville", slug: "louisville", keyword: "AI dental software Louisville" },
  { name: "Baltimore", slug: "baltimore", keyword: "AI dental software Baltimore" },
  { name: "Milwaukee", slug: "milwaukee", keyword: "AI dental software Milwaukee" },
  { name: "Albuquerque", slug: "albuquerque", keyword: "AI dental software Albuquerque" },
  { name: "Tucson", slug: "tucson", keyword: "AI dental software Tucson" },
  { name: "Fresno", slug: "fresno", keyword: "AI dental software Fresno" },
  { name: "Mesa", slug: "mesa", keyword: "AI dental software Mesa" },
  { name: "Sacramento", slug: "sacramento", keyword: "AI dental software Sacramento" },
  { name: "Atlanta", slug: "atlanta", keyword: "AI dental software Atlanta" },
  { name: "Kansas City", slug: "kansas-city", keyword: "AI dental software Kansas City" },
  { name: "Colorado Springs", slug: "colorado-springs", keyword: "AI dental software Colorado Springs" },
  { name: "Miami", slug: "miami", keyword: "AI dental software Miami" },
  { name: "Raleigh", slug: "raleigh", keyword: "AI dental software Raleigh" },
  { name: "Omaha", slug: "omaha", keyword: "AI dental software Omaha" },
  { name: "Long Beach", slug: "long-beach", keyword: "AI dental software Long Beach" },
  { name: "Virginia Beach", slug: "virginia-beach", keyword: "AI dental software Virginia Beach" },
  { name: "Oakland", slug: "oakland", keyword: "AI dental software Oakland" },
  { name: "Minneapolis", slug: "minneapolis", keyword: "AI dental software Minneapolis" },
  { name: "Tulsa", slug: "tulsa", keyword: "AI dental software Tulsa" },
  { name: "Arlington", slug: "arlington", keyword: "AI dental software Arlington" },
  { name: "Tampa", slug: "tampa", keyword: "AI dental software Tampa" },
  { name: "New Orleans", slug: "new-orleans", keyword: "AI dental software New Orleans" },
  { name: "Wichita", slug: "wichita", keyword: "AI dental software Wichita" },
  { name: "Cleveland", slug: "cleveland", keyword: "AI dental software Cleveland" },
  { name: "Bakersfield", slug: "bakersfield", keyword: "AI dental software Bakersfield" },
  { name: "Aurora", slug: "aurora", keyword: "AI dental software Aurora" },
  { name: "Anaheim", slug: "anaheim", keyword: "AI dental software Anaheim" },
  { name: "Honolulu", slug: "honolulu", keyword: "AI dental software Honolulu" },
  { name: "Santa Ana", slug: "santa-ana", keyword: "AI dental software Santa Ana" },
  { name: "Riverside", slug: "riverside", keyword: "AI dental software Riverside" },
  { name: "Corpus Christi", slug: "corpus-christi", keyword: "AI dental software Corpus Christi" },
  { name: "Lexington", slug: "lexington", keyword: "AI dental software Lexington" },
  { name: "Henderson", slug: "henderson", keyword: "AI dental software Henderson" },
  { name: "Stockton", slug: "stockton", keyword: "AI dental software Stockton" },
  { name: "Saint Paul", slug: "saint-paul", keyword: "AI dental software Saint Paul" },
  { name: "Cincinnati", slug: "cincinnati", keyword: "AI dental software Cincinnati" },
  { name: "St. Louis", slug: "st-louis", keyword: "AI dental software St. Louis" },
  { name: "Pittsburgh", slug: "pittsburgh", keyword: "AI dental software Pittsburgh" },
  { name: "Greensboro", slug: "greensboro", keyword: "AI dental software Greensboro" },
  { name: "Lincoln", slug: "lincoln", keyword: "AI dental software Lincoln" },
  { name: "Anchorage", slug: "anchorage", keyword: "AI dental software Anchorage" },
  { name: "Plano", slug: "plano", keyword: "AI dental software Plano" },
  { name: "Orlando", slug: "orlando", keyword: "AI dental software Orlando" },
  { name: "Irvine", slug: "irvine", keyword: "AI dental software Irvine" },
  { name: "Newark", slug: "newark", keyword: "AI dental software Newark" },
  { name: "Durham", slug: "durham", keyword: "AI dental software Durham" },
  { name: "Chula Vista", slug: "chula-vista", keyword: "AI dental software Chula Vista" },
  { name: "Toledo", slug: "toledo", keyword: "AI dental software Toledo" },
  { name: "Fort Wayne", slug: "fort-wayne", keyword: "AI dental software Fort Wayne" },
  { name: "St. Petersburg", slug: "st-petersburg", keyword: "AI dental software St. Petersburg" },
  { name: "Laredo", slug: "laredo", keyword: "AI dental software Laredo" },
  { name: "Jersey City", slug: "jersey-city", keyword: "AI dental software Jersey City" },
  { name: "Chandler", slug: "chandler", keyword: "AI dental software Chandler" },
  { name: "Madison", slug: "madison", keyword: "AI dental software Madison" },
  { name: "Lubbock", slug: "lubbock", keyword: "AI dental software Lubbock" },
  { name: "Scottsdale", slug: "scottsdale", keyword: "AI dental software Scottsdale" },
  { name: "Reno", slug: "reno", keyword: "AI dental software Reno" },
  { name: "Buffalo", slug: "buffalo", keyword: "AI dental software Buffalo" },
  { name: "Gilbert", slug: "gilbert", keyword: "AI dental software Gilbert" },
  { name: "Glendale", slug: "glendale", keyword: "AI dental software Glendale" },
  { name: "North Las Vegas", slug: "north-las-vegas", keyword: "AI dental software North Las Vegas" },
  { name: "Winston–Salem", slug: "winston-salem", keyword: "AI dental software Winston–Salem" }
];
wq

