export const cities = [
  { name: "New York", slug: "new-york" },
  { name: "Los Angeles", slug: "los-angeles" },
  { name: "Chicago", slug: "chicago" },
  { name: "Houston", slug: "houston" },
  { name: "Phoenix", slug: "phoenix" },
  { name: "Philadelphia", slug: "philadelphia" },
  { name: "San Antonio", slug: "san-antonio" },
  { name: "San Diego", slug: "san-diego" },
  { name: "Dallas", slug: "dallas" },
  { name: "San Jose", slug: "san-jose" },
  { name: "Austin", slug: "austin" },
  { name: "Jacksonville", slug: "jacksonville" },
  { name: "Fort Worth", slug: "fort-worth" },
  { name: "Columbus", slug: "columbus" },
  { name: "Charlotte", slug: "charlotte" },
  { name: "San Francisco", slug: "san-francisco" },
  { name: "Indianapolis", slug: "indianapolis" },
  { name: "Seattle", slug: "seattle" },
  { name: "Denver", slug: "denver" },
  { name: "Washington", slug: "washington" },
  { name: "Boston", slug: "boston" },
  { name: "El Paso", slug: "el-paso" },
  { name: "Nashville", slug: "nashville" },
  { name: "Detroit", slug: "detroit" },
  { name: "Oklahoma City", slug: "oklahoma-city" },
  { name: "Portland", slug: "portland" },
  { name: "Las Vegas", slug: "las-vegas" },
  { name: "Memphis", slug: "memphis" },
  { name: "Louisville", slug: "louisville" },
  { name: "Baltimore", slug: "baltimore" },
  { name: "Milwaukee", slug: "milwaukee" },
  { name: "Albuquerque", slug: "albuquerque" },
  { name: "Tucson", slug: "tucson" },
  { name: "Fresno", slug: "fresno" },
  { name: "Mesa", slug: "mesa" },
  { name: "Sacramento", slug: "sacramento" },
  { name: "Atlanta", slug: "atlanta" },
  { name: "Kansas City", slug: "kansas-city" },
  { name: "Colorado Springs", slug: "colorado-springs" },
  { name: "Miami", slug: "miami" },
  { name: "Raleigh", slug: "raleigh" },
  { name: "Omaha", slug: "omaha" },
  { name: "Long Beach", slug: "long-beach" },
  { name: "Virginia Beach", slug: "virginia-beach" },
  { name: "Oakland", slug: "oakland" },
  { name: "Minneapolis", slug: "minneapolis" },
  { name: "Tulsa", slug: "tulsa" },
  { name: "Arlington", slug: "arlington" },
  { name: "New Orleans", slug: "new-orleans" },
  { name: "Wichita", slug: "wichita" },
  { name: "Cleveland", slug: "cleveland" },
  { name: "Tampa", slug: "tampa" },
  { name: "Bakersfield", slug: "bakersfield" },
  { name: "Aurora", slug: "aurora" },
  { name: "Honolulu", slug: "honolulu" },
  { name: "Anaheim", slug: "anaheim" },
  { name: "Santa Ana", slug: "santa-ana" },
  { name: "Riverside", slug: "riverside" },
  { name: "Corpus Christi", slug: "corpus-christi" },
  { name: "Lexington", slug: "lexington" },
  { name: "Henderson", slug: "henderson" },
  { name: "Stockton", slug: "stockton" },
  { name: "Saint Paul", slug: "saint-paul" },
  { name: "Cincinnati", slug: "cincinnati" },
  { name: "St. Louis", slug: "st-louis" },
  { name: "Pittsburgh", slug: "pittsburgh" },
  { name: "Greensboro", slug: "greensboro" },
  { name: "Lincoln", slug: "lincoln" },
  { name: "Anchorage", slug: "anchorage" },
  { name: "Plano", slug: "plano" },
  { name: "Orlando", slug: "orlando" },
  { name: "Irvine", slug: "irvine" },
  { name: "Newark", slug: "newark" },
  { name: "Toledo", slug: "toledo" },
  { name: "Durham", slug: "durham" },
  { name: "Chula Vista", slug: "chula-vista" },
  { name: "Fort Wayne", slug: "fort-wayne" },
  { name: "Jersey City", slug: "jersey-city" },
  { name: "St. Petersburg", slug: "st-petersburg" },
  { name: "Laredo", slug: "laredo" },
  { name: "Madison", slug: "madison" },
  { name: "Chandler", slug: "chandler" },
  { name: "Buffalo", slug: "buffalo" },
  { name: "Lubbock", slug: "lubbock" },
  { name: "Scottsdale", slug: "scottsdale" },
  { name: "Reno", slug: "reno" },
  { name: "Glendale", slug: "glendale" },
  { name: "Gilbert", slug: "gilbert" },
  { name: "Winston–Salem", slug: "winston-salem" },
  { name: "North Las Vegas", slug: "north-las-vegas" },
  { name: "Norfolk", slug: "norfolk" },
  { name: "Chesapeake", slug: "chesapeake" },
  { name: "Garland", slug: "garland" },
  { name: "Irving", slug: "irving" },
  { name: "Hialeah", slug: "hialeah" },
  { name: "Fremont", slug: "fremont" },
  { name: "Boise", slug: "boise" },
  { name: "Richmond", slug: "richmond" }
];

